### PR TITLE
Add Russian recourses

### PR DESCRIPTION
**Pull request by Dvornik**
Added resource files for Russian language:
kdkwp
f8kit
etc.

### CODE REVIEW

**Comment by charlesmilette** [comment]
You just gave me a great idea! Time to translate.

**Comment by charlesmilette** [comment]
Hey, what does `NavigateLink` means? It's confusing me.

**Comment by Dvornik** [comment]
@charlesmilette 
7v3yv

**Comment by charlesmilette** [comment]
I knew that it means that, but where does the string appear?

If it appears in a tooltip, I'd go for "Naviguer vers le lien"
Somewhere else, I'll use "Lien de navigation"
Etc...

That's why I'd like to know _where_ does it appears

**Comment by Dvornik** [comment]
@charlesmilette 
Is used only here:

```
namespace FirstFloor.ModernUI.Windows.Navigation
{
    /// <summary>
    /// The routed link commands.
    /// </summary>
    public static class LinkCommands
    {
        private static RoutedUICommand navigateLink = new RoutedUICommand(Resources.NavigateLink, "NavigateLink", typeof(LinkCommands));

        /// <summary>
        /// Gets the navigate link routed command.
        /// </summary>
        public static RoutedUICommand NavigateLink
        {
            get { return navigateLink; }
        }
    }
} 
```
No example for tooltip etc in sample app. I translated it verbatim.

**Comment by charlesmilette** [comment]
Thanks!

**Comment by kungfux** [comment]
@Dvornik Why every Russian translation begins with lower-case letter? And why "ok" is written in English but not in Russian "ок"? This looks pretty strange. Thanks in advance.

**Comment by Dvornik** [comment]
@kungfux Good question. 

I left as it was in the English version, for consistency. MUI **automatically** changed capitalization for tabs'  and sub tabs' headings, so  lower-case looks appropriate.

But I agree, that is look unusually for Cyrillic. I re-read guidline https://msdn.microsoft.com/windows/uwp/style/typography - ALL CAP recommended only for certain pages, no information about lower-case, so I'll fix it.

I'm thinking about adding property for turn on/ turn off automatic capitalization changing.

**Comment by kungfux** [comment]
@Dvornik Thanks for reply. 

As I can see in this repository and your fork as well, the 1st letter is upper-case for English translation. But it's okay if you are going to change the Russian translation in correct way. 

By the way, do you know, does appropriate translation is chosen automatically at runtime or startup based on system codepage? As I understand the answer is no. Is it so?

**Comment by Dvornik** [comment]
> As I can see in this repository and your fork as well, the 1st letter is upper-case for English translation. 

@kungfux It's not:
zjxp6
MUI **convert case at runtime** for styling purpose. I can't fix it with just in resource file. In my res file, the first key is upper-case too.
@charlesmilette can't change it too only with res file.

I think the best solution is adding property for turn on/ turn off automatic capitalization changing.

> translation is chosen automatically at runtime or startup based on system codepage

Exactly: it' standard WPF behavior, not just MUI. Very useful.

**Comment by kungfux** [comment]
@Dvornik I meant English translations in the [code](https://github.com/firstfloorsoftware/mui/blob/master/1.0/FirstFloor.ModernUI/Shared/Resources.Designer.cs#L212)

> Exactly: it' standard WPF behavior, not just MUI. Very useful. No additional code needed.

Great, thanks!

**Comment by Dvornik** [comment]
> I meant English translations in the code

@kungfux Is just resource designer's auto-generated file. The right file with translation: https://github.com/firstfloorsoftware/mui/blob/master/1.0/FirstFloor.ModernUI/Shared/Resources.resx

**Comment by kungfux** [comment]
@Dvornik Got it. You're right. Thanks for your time.

**Pull request merged**
