### PR TITLE
Added Modern Toggle Button

### PR DESCRIPTION
**Pull request by Quppa**
Almost identical to Modern Button but inherits from ToggleButton so has
checked and unchecked states.

### CODE REVIEW

**Comment by wdhodges** [comment]
Is ModernUI still on the upkeep? I just haven't seen any commits by the author in 4 months.

**Comment by Quppa** [comment]
It doesn't seem very active, though 4 months isn't an especially long time. The project is pretty good as it is, anyway.

**Comment by wdhodges** [comment]
This is very very true. Just wish I could figure how to save a user configuration to keep their color and theme (light or dark)

On Aug 2, 2015 8:03 AM, David Warner <notifications@github.com> wrote:

It doesn't seem very active, though 4 months isn't an especially long time. The project is pretty good as it is, anyway.

**Comment by niravraval** [comment]
Ohhh I did this part… Will update the code early in the morning…. 😊 I always save the last configuration of user, So, on the next login, it looks very same as last one 😊


And yes, this is really helpful project for people like me (who are dumb in designing) 😊


Happy coding…






Sent from Windows Mail





From: William Hodges
Sent: ‎Sunday‎, ‎02‎ ‎August‎ ‎2015 ‎17‎:‎37
To: firstfloorsoftware/mui




This is very very true. Just wish I could figure how to save a user configuration to keep their color and theme (light or dark) 

On Aug 2, 2015 8:03 AM, David Warner <notifications@github.com> wrote: 

It doesn't seem very active, though 4 months isn't an especially long time. The project is pretty good as it is, anyway.

**Comment by FuchsiaSoft** [comment]
This has been raised as its own issue in #49

I have provided a sample solution on that issue to address the request for
persisting user settings.

**Pull request merged**
