### PR TITLE
Added French Translation

### PR DESCRIPTION
**Pull request by sylveon**
capture

### CODE REVIEW

**Comment by kungfux** [comment]
@charlesmilette Looks like your changes needs to be re-done as well. Please refer to the comments for another pull request https://github.com/firstfloorsoftware/mui/pull/96

**Comment by Dvornik** [comment]
Or not, if it look ok in French like it look in English)

**Comment by kungfux** [comment]
Just up to you, guys. As for me, it should be changed for English as well to be standard and consistent.

**Comment by Dvornik** [comment]
> changed for English as well to be standard and consistent.
Sounds good. Especially since all-lower-case style is not suitable for the German.

**Comment by kungfux** [comment]
@kozw Sorry for troubling you. Could you please provide your vision? Is it good idea to change the resource strings to have each string started with upper-case letter for English resources?

**Comment by kozw** [comment]
Starting with an upper-case letter is a matter of taste. When I started this project, I liked it, now I'm not too thrilled about it and would suggest to capitalize the resource strings.

**Comment by kozw** [comment]
There are conflicts with this branch. Care to submit a new PR based on the most recent master?

**Comment by charlesmilette** [comment]
I don't have VS installed right now, because I clean installed Windows since I made this PR. But you can take the strings I wrote and directly add them to the project, I don't really care.

**Comment by kozw** [comment]
Fixed in https://github.com/firstfloorsoftware/mui/commit/cbd78931b5ffd1a77c8a82a423100e11015203c2

**Pull request closed without merging**
